### ISSUE TITLE
dnsminder won't work on ubuntu 24.04

### ISSUE THREAD

**Issue by prascher** [jeremehancock/dnsminder#3]
I can't get dnsminder to run on Ubuntu 24.04, nor can I uninstall it.  From what I can tell it appears to be a change in the Ubuntu 24.04 DNS resolver.

**Comment by prascher** [comment]
Update it appears the problems are related to resolvconf not being a service on Ubuntu 24.04.

**Comment by jeremehancock** [comment]
@prascher Thank you for the report. UbuntuCE's repos and packages are currently only established for Ubuntu 22.04. Once Ubuntu 24.04 hits it's first point release we will begin the process of creating the new iso and repos for the next major release of UbuntuCE.

Thanks again
